import { StyleSheet } from 'react-native';

const stiller = StyleSheet.create({
  disKapsayici: {
    flex: 1,
    paddingTop: 54,
    paddingHorizontal: 14,
  },
  sayfaIcerik: {
    paddingBottom: 28,
  },
  ustBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  ustAksiyonKolon: {
    gap: 8,
  },
  yuvarlakMiniButon: {
    width: 40,
    height: 40,
    borderRadius: 999,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.17)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.26)',
  },
  yuvarlakMiniButonYazi: {
    fontSize: 17,
  },
  yuklemeKart: {
    marginTop: 80,
    borderRadius: 18,
    padding: 20,
    backgroundColor: 'rgba(255,255,255,0.12)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.18)',
  },
  yuklemeBaslik: {
    fontSize: 30,
    fontWeight: '800',
    color: '#FFFFFF',
    textAlign: 'center',
  },
  yuklemeMetni: {
    marginTop: 8,
    fontSize: 14,
    color: '#CFE0FF',
    textAlign: 'center',
  },
  ustBaslikSatiri: {
    marginBottom: 10,
  },
  markaYazisi: {
    fontSize: 30,
    fontWeight: '800',
    color: '#FFFFFF',
    letterSpacing: 0.6,
  },
  markaAltYazi: {
    marginTop: 3,
    fontSize: 14,
    color: '#D4E5FF',
    fontWeight: '600',
  },
  kart: {
    width: '100%',
    borderRadius: 18,
    padding: 16,
    marginBottom: 12,
    backgroundColor: 'rgba(255,255,255,0.16)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.22)',
  },
  kartBaslik: {
    fontSize: 22,
    color: '#FFFFFF',
    fontWeight: '800',
    textAlign: 'left',
  },
  kartAciklama: {
    marginTop: 6,
    marginBottom: 12,
    fontSize: 14,
    color: '#D2E3FF',
    textAlign: 'center',
    lineHeight: 21,
  },
  petSahne: {
    alignItems: 'center',
    paddingVertical: 8,
    marginBottom: 10,
    position: 'relative',
  },
  petEmoji: {
    fontSize: 88,
    textAlign: 'center',
    marginBottom: 2,
  },
  aksesuarRozeti: {
    position: 'absolute',
    right: '36%',
    top: 4,
    fontSize: 28,
  },
  ifadeRozeti: {
    marginTop: 6,
    borderRadius: 12,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 4,
    backgroundColor: 'rgba(0,0,0,0.18)',
  },
  ifadeRozetiYazi: {
    fontSize: 12,
    color: '#F8FBFF',
    fontWeight: '700',
  },
  petAdYazi: {
    fontSize: 16,
    color: '#FFFFFF',
    fontWeight: '700',
  },
  petTurYazi: {
    marginTop: 2,
    fontSize: 12,
    color: '#D9E8FF',
    fontWeight: '600',
  },
  menuGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 12,
  },
  menuBilgiKart: {
    flexBasis: '48%',
    borderRadius: 12,
    paddingVertical: 8,
    backgroundColor: 'rgba(255,255,255,0.12)',
  },
  menuBilgiEtiket: {
    textAlign: 'center',
    fontSize: 11,
    color: '#C9DBFA',
    fontWeight: '600',
  },
  menuBilgiDeger: {
    marginTop: 3,
    textAlign: 'center',
    fontSize: 15,
    color: '#FFFFFF',
    fontWeight: '800',
  },
  petSecimSatiri: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 12,
  },
  petSecimKarti: {
    flex: 1,
    borderRadius: 12,
    paddingVertical: 10,
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.2)',
  },
  petSecimKartiAktif: {
    backgroundColor: 'rgba(157, 240, 255, 0.2)',
    borderColor: 'rgba(157, 240, 255, 0.65)',
  },
  petSecimEmoji: {
    fontSize: 28,
  },
  petSecimAd: {
    marginTop: 4,
    fontSize: 12,
    color: '#F4F8FF',
    fontWeight: '700',
  },
  baslik: {
    fontSize: 26,
    fontWeight: '800',
    color: '#FFFFFF',
    textAlign: 'left',
  },
  mesaj: {
    fontSize: 15,
    color: '#E8F0FF',
    textAlign: 'center',
    marginBottom: 14,
    lineHeight: 22,
    fontWeight: '600',
  },
  statSatiri: {
    marginBottom: 12,
  },
  statBaslikSatiri: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 6,
  },
  statEtiketi: {
    fontSize: 14,
    color: '#F2F6FF',
    fontWeight: '700',
  },
  statDegeri: {
    fontSize: 14,
    color: '#FFFFFF',
    fontWeight: '800',
  },
  cubukDis: {
    height: 11,
    borderRadius: 99,
    overflow: 'hidden',
  },
  cubukIc: {
    height: '100%',
    borderRadius: 99,
  },
  puanKutusu: {
    marginTop: 3,
    marginBottom: 10,
    paddingVertical: 10,
    borderRadius: 12,
    backgroundColor: 'rgba(255,255,255,0.18)',
  },
  puanYazisi: {
    textAlign: 'center',
    fontSize: 17,
    color: '#FFFFFF',
    fontWeight: '800',
  },
  enYuksekPuanYazisi: {
    textAlign: 'center',
    fontSize: 14,
    color: '#DCE7FF',
    fontWeight: '700',
    marginTop: 4,
  },
  seviyeKutusu: {
    marginBottom: 10,
    padding: 10,
    borderRadius: 12,
    backgroundColor: 'rgba(8, 23, 40, 0.35)',
    borderWidth: 1,
    borderColor: 'rgba(181, 221, 255, 0.25)',
  },
  seviyeUstSatir: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 7,
  },
  seviyeBaslik: {
    fontSize: 15,
    fontWeight: '800',
    color: '#FFFFFF',
  },
  seviyeXpYazisi: {
    fontSize: 13,
    color: '#D2E6FF',
    fontWeight: '700',
  },
  seviyeCubuguDis: {
    height: 10,
    borderRadius: 99,
    overflow: 'hidden',
    backgroundColor: 'rgba(255,255,255,0.2)',
  },
  seviyeCubuguIc: {
    height: '100%',
    borderRadius: 99,
    backgroundColor: '#85C9FF',
  },
  basarimKutusu: {
    marginBottom: 10,
    padding: 10,
    borderRadius: 12,
    backgroundColor: 'rgba(255,255,255,0.1)',
  },
  basarimBaslik: {
    fontSize: 14,
    color: '#FFFFFF',
    fontWeight: '800',
  },
  basarimAltMetin: {
    marginTop: 2,
    marginBottom: 8,
    fontSize: 12,
    color: '#D4E2F3',
    fontWeight: '500',
  },
  basarimRozetSatiri: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  rozet: {
    paddingHorizontal: 8,
    paddingVertical: 6,
    borderRadius: 10,
    borderWidth: 1,
  },
  rozetAcik: {
    backgroundColor: 'rgba(129, 241, 174, 0.2)',
    borderColor: 'rgba(129, 241, 174, 0.55)',
  },
  rozetKilitli: {
    backgroundColor: 'rgba(255,255,255,0.06)',
    borderColor: 'rgba(255,255,255,0.18)',
  },
  rozetYazisi: {
    fontSize: 11,
    color: '#ECF4FF',
    fontWeight: '700',
  },
  rozetAciklama: {
    marginTop: 3,
    fontSize: 10,
    color: '#CFE0FA',
    fontWeight: '500',
  },
  basarimBildirimKutusu: {
    marginBottom: 12,
    paddingVertical: 8,
    borderRadius: 10,
    backgroundColor: 'rgba(255, 217, 110, 0.2)',
    borderWidth: 1,
    borderColor: 'rgba(255, 217, 110, 0.55)',
  },
  basarimBildirimBaslik: {
    textAlign: 'center',
    fontSize: 12,
    color: '#FFE8A3',
    fontWeight: '700',
  },
  basarimBildirimMetni: {
    textAlign: 'center',
    marginTop: 2,
    fontSize: 14,
    color: '#FFF8DF',
    fontWeight: '700',
  },
  seviyeBildirimKutusu: {
    marginBottom: 10,
    borderRadius: 10,
    backgroundColor: 'rgba(133, 201, 255, 0.22)',
    borderWidth: 1,
    borderColor: 'rgba(133, 201, 255, 0.58)',
    paddingVertical: 8,
  },
  seviyeBildirimMetni: {
    textAlign: 'center',
    color: '#E8F5FF',
    fontSize: 13,
    fontWeight: '800',
  },
  gunlukGorevKutusu: {
    marginBottom: 10,
    padding: 10,
    borderRadius: 12,
    backgroundColor: 'rgba(255,255,255,0.1)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.18)',
  },
  gunlukGorevBaslik: {
    fontSize: 14,
    color: '#FFFFFF',
    fontWeight: '800',
  },
  gunlukGorevMetni: {
    marginTop: 4,
    fontSize: 13,
    color: '#E8F2FF',
    fontWeight: '600',
  },
  gunlukGorevIlerleme: {
    marginTop: 6,
    fontSize: 12,
    color: '#D5E7FF',
    fontWeight: '600',
  },
  gunlukGorevOdul: {
    marginTop: 2,
    fontSize: 12,
    color: '#CFE8D1',
    fontWeight: '600',
  },
  streakYazisi: {
    marginTop: 4,
    fontSize: 12,
    color: '#FFE4AF',
    fontWeight: '800',
  },
  butonSatiri: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 4,
  },
  buton: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 13,
    borderRadius: 12,
    borderWidth: 1,
  },
  butonTamGenislik: {
    width: '100%',
    marginTop: 4,
    marginBottom: 2,
  },
  butonBirincil: {
    backgroundColor: '#FFFFFF',
    borderColor: '#FFFFFF',
  },
  butonIkincil: {
    backgroundColor: 'rgba(42, 61, 96, 0.75)',
    borderColor: 'rgba(255,255,255,0.35)',
  },
  butonVurgu: {
    backgroundColor: '#79DEB8',
    borderColor: '#79DEB8',
  },
  butonDevreDisi: {
    opacity: 0.45,
  },
  butonYazisi: {
    fontSize: 15,
    fontWeight: '800',
  },
  butonYazisiKoyu: {
    color: '#1F2D46',
  },
  butonYazisiAcik: {
    color: '#F4F8FF',
  },
  yenidenBaslaAlan: {
    marginTop: 10,
  },
  kaybetmeKart: {
    marginTop: 10,
    marginBottom: 4,
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: 'rgba(255, 133, 133, 0.6)',
    backgroundColor: 'rgba(127, 29, 29, 0.35)',
  },
  kaybetmeBaslik: {
    fontSize: 17,
    color: '#FFE4E4',
    fontWeight: '800',
    textAlign: 'center',
  },
  kaybetmeMetin: {
    marginTop: 4,
    fontSize: 13,
    color: '#FAD3D3',
    textAlign: 'center',
    lineHeight: 20,
    fontWeight: '600',
  },
  oyunUstSatir: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  kucukMenuButon: {
    borderRadius: 999,
    paddingVertical: 7,
    paddingHorizontal: 12,
    backgroundColor: 'rgba(255,255,255,0.2)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.3)',
  },
  kucukMenuButonYazi: {
    fontSize: 11,
    color: '#F2F7FF',
    fontWeight: '800',
  },
  sezonGorevListesi: {
    gap: 8,
  },
  sezonGorevKart: {
    borderRadius: 12,
    padding: 10,
    backgroundColor: 'rgba(255,255,255,0.1)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.15)',
  },
  sezonGorevBaslik: {
    fontSize: 13,
    color: '#FFFFFF',
    fontWeight: '800',
  },
  sezonGorevIlerleme: {
    marginTop: 4,
    fontSize: 12,
    color: '#D4E5FF',
    fontWeight: '600',
  },
  magazaListe: {
    gap: 8,
  },
  magazaKart: {
    borderRadius: 12,
    padding: 10,
    backgroundColor: 'rgba(255,255,255,0.12)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.2)',
  },
  magazaRenkOrnek: {
    height: 18,
    borderRadius: 8,
    marginBottom: 8,
  },
  magazaAksesuarEmoji: {
    fontSize: 28,
    marginBottom: 6,
  },
  magazaBilgi: {
    marginBottom: 8,
  },
  magazaBaslik: {
    fontSize: 14,
    color: '#FFFFFF',
    fontWeight: '800',
  },
  magazaFiyat: {
    marginTop: 2,
    fontSize: 12,
    color: '#D3E5FF',
    fontWeight: '600',
  },
  modalKaplama: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    paddingHorizontal: 18,
  },
  modalKart: {
    borderRadius: 16,
    padding: 16,
    backgroundColor: '#172949',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.25)',
  },
  kaybetmeModalKart: {
    borderRadius: 16,
    padding: 16,
    backgroundColor: '#3A1B2A',
    borderWidth: 1,
    borderColor: 'rgba(255, 162, 162, 0.5)',
  },
  modalBaslik: {
    fontSize: 20,
    color: '#FFFFFF',
    fontWeight: '800',
    textAlign: 'center',
  },
  modalMetin: {
    marginTop: 8,
    fontSize: 14,
    lineHeight: 21,
    color: '#D4E8FF',
    textAlign: 'center',
  },
  modalButonSatiri: {
    marginTop: 12,
    gap: 8,
  },
  etkinlikSecenekKart: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(155, 221, 255, 0.45)',
    padding: 10,
    backgroundColor: 'rgba(255,255,255,0.08)',
  },
  etkinlikSecenekBaslik: {
    fontSize: 14,
    color: '#FFFFFF',
    fontWeight: '800',
  },
  etkinlikSecenekSonuc: {
    marginTop: 4,
    fontSize: 12,
    color: '#CFE5FF',
    fontWeight: '600',
  },
  toastKutusu: {
    position: 'absolute',
    left: 16,
    right: 16,
    bottom: 14,
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 12,
    backgroundColor: 'rgba(9, 20, 39, 0.9)',
    borderWidth: 1,
    borderColor: 'rgba(134, 214, 255, 0.4)',
  },
  toastYazi: {
    textAlign: 'center',
    color: '#EAF5FF',
    fontSize: 12,
    fontWeight: '700',
  },
  hesapAltBaslik: {
    marginTop: 8,
    marginBottom: 8,
    fontSize: 14,
    color: '#F6FAFF',
    fontWeight: '800',
  },
  istatistikSatiri: {
    borderRadius: 12,
    padding: 12,
    backgroundColor: 'rgba(255,255,255,0.12)',
  },
  istatistikYazi: {
    fontSize: 13,
    color: '#E4EEFF',
    fontWeight: '700',
    marginBottom: 5,
  },
});

export default stiller;
